### ISSUE TITLE
How to support Korean / Chinese and Japanese languages ?

### ISSUE THREAD

**Issue by YuManZz** [Setasign/tFPDF#10]
Hi,

I'm using TFPDF since yesterday, before I was on FPDF (Big trouble with non-latin language).

I have fix the problem for Cyrillic language just with the change to tFPDF but others non-latin language still not working.

```
public function createPDF() {

        $pdf = new tFPDF();
        $pdf->AddPage();

// Add a Unicode font (uses UTF-8)
//        $pdf->AddFont('DejaVu','','DejaVuSansCondensed.ttf',true);
        $pdf->AddFont('DejaVu','','DejaVuSans.ttf',true);
        $pdf->SetFont('DejaVu','',14);

        $pdf->Write(8,'이것은 시험이다');

        $pdf->Output();
}
```

I continue to have square instead of good characters.

What can I do to fix this ?

And I need to add this languages in my documents at any time, I don't know if my string could be with non-latin characters.

Thanks ! :)

**Comment by shinsenter** [comment]
@YuManZz 
I fixed this by using the built-in Arial font of macOS.

**Comment by JanSlabon** [comment]
Make sure that the font covers the scripts you need. DejaVu doesn't covers yours: https://dejavu-fonts.github.io/
