### ISSUE TITLE
这个能导出中文吗

### ISSUE THREAD

**Issue by jackmingren** [Setasign/tFPDF#16]
Can I export Chinese files

**Comment by JanSlabon** [comment]
If you use a font with Chinese characters this shouldn't be a problem? Did you tried it?

**Comment by jackmingren** [comment]
My friend, I tested it and it seems like I can't export Chinese。Is there no Chinese font file in this package?

**Comment by JanSlabon** [comment]
The only font that is in this package is DejaVu which is not a Chinese one.
You may give Noto a try: https://fonts.google.com/noto/specimen/Noto+Sans+SC

**Comment by jackmingren** [comment]
thank you
