### ISSUE TITLE
After update failed opening ttfonts.php

### ISSUE THREAD

**Issue by mushtaqx** [Setasign/tFPDF#3]
` "message": "tFPDF::_putfonts(): Failed opening required '/var/www/<LARAVEL PROJECT>/storage/app/pdf/unifont/ttfonts.php' (include_path='.:/usr/share/php')",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/var/www/<LARAVEL PROJECT>/vendor/setasign/tfpdf/tfpdf.php",
    "line": 1896,
`
If i create an empty ttfonts.php where its searching, problem solves.

**Comment by d3sirous** [comment]
Changing /vendor/setasign/tfpdf/tfpdf.php line 1896 to
`require_once(__DIR__.'/font/unifont/ttfonts.php');`
solves the problem and also regenerates my custom fonts but iam not sure what other implications this might have aside from fixing this issue. @JanSlabon

**Comment by JanSlabon** [comment]
The mentioned class/file is normally loaded by composer automatically. If you do not install the library via composer, please use the official version which has the line uncommented: http://fpdf.org/en/script/script92.php

**Comment by JanSlabon** [comment]
Wait, you're right that this line is somewhat faulty.
It needs to be commented, too. Will do and re-release asap.

**Comment by mushtaqx** [comment]
Thanks for the fix, much appreciated!

**Comment by mushtaqx** [comment]
Reopened for a packagist update.

**Comment by JanSlabon** [comment]
Re-released... it was not a sync issue but the version number was still outdated in the composer.json file. Thanks for reporting!
