### ISSUE TITLE
.gitignore exludes font/unifont/ttfonts.php

### ISSUE THREAD

**Issue by drjayvee** [Setasign/tFPDF#4]
Maybe this is by design, but I'm wondering why the `.gitignore` contains the line `font/unifont/*.php`, when `font/unifont/ttfonts.php` is required as an `autoload` in `composer.json`.

Maybe the point was to exclude generated files like `font/unifont/dejavu.mtx.php`.

In that case, I would propose changing the `.gitignore` line to read `font/unifont/*.*.*`, which excludes `*.cw.dat`, `*.mtx.php` and `*.cw127.php`, but **not** `ttfonts.php`.

Background: I'm running into this because our project's code delivery basically does
```
composer install
git add --all .
git push production HEAD
```
Since this update, `vendor/setasign/tfpdf/font/unifont/ttfonts.php` is excluded, which causes problems. I can fix this in other ways, but I wanted to raise this issue.

**Comment by JanSlabon** [comment]
For sure you are right. It was meant to execlude generated files only.

I just added your suggestion which seems to work. Can you verify this through the master?

**Comment by drjayvee** [comment]
Verify? You mean create a PR against master? I'd be happy to.

Edit: nevermind, I understand what you meant. Currently testing...

**Comment by JanSlabon** [comment]
:-) No, I already updated [`.gitignore`](https://github.com/Setasign/tFPDF/commit/f8502b2a69130b2bde6a41a801bbc6db40e05f8a) in the master. I just wanted to know if you have a way to test `"setasign/tfpdf": "dev-master"` in combination with this:

     composer install
     git add --all .
     git push soemthing-else HEAD

?

**Comment by drjayvee** [comment]
:D I can confirm that the `.gitignore` works as it did previously. 👍

**Comment by drjayvee** [comment]
Will you create a new release straight away? Otherwise I'll implement the workaround (`git add -f ...`) for the time being.

**Comment by JanSlabon** [comment]
Here you go: https://github.com/Setasign/tFPDF/releases/tag/v1.31.2
