### ISSUE TITLE
Incorrect russian translation in example

### ISSUE THREAD

**Issue by moshkalev** [Setasign/tFPDF#7]
"Hello, world" = "Привет, мир!"

**Comment by JanSlabon** [comment]
> This repository is only made for cloning official tFPDF releases which are available at: http://fpdf.org/en/script/script92.php THERE WILL BE NO DEVELOPMENT IN THIS REPOSITORY!

You may file this in the FPDF forum, so that the original package gets updated (if this is really a serious issue ;-))
