### ISSUE TITLE
PHP8.2 support

### ISSUE THREAD

**Issue by shinsenter** [Setasign/tFPDF#9]
PHP8.2 was released few days ago. After migration, I got these errors:

```
A PHP Error was encountered
Severity: 8192
Message: Creation of dynamic property TTFontFile::$maxUniChar is deprecated
Filename: unifont/ttfonts.php
Line Number: 991
Backtrace:
File: /var/www/html/vendor/setasign/tfpdf/font/unifont/ttfonts.php
Line: 991
```

So, I think it would be better if the library can support PHP8.2.

Best regards.

**Comment by JanSlabon** [comment]
I just asked for the missing properties in the FPDF forum [here](http://www.fpdf.org/phorum/read.php?f=1&i=62721&t=62721).

**Comment by shinsenter** [comment]
@JanSlabon oh, great to know that. Thank you!

**Comment by JanSlabon** [comment]
FYI: This is fixed in the latest release: https://github.com/Setasign/tFPDF/releases/tag/v1.33
